[package]
name = "cosmwasm-bignumber"
version = "1.0.0"
authors = ["Terraform Labs, PTE."]
edition = "2018"
description = "Bignumber library for cosmwasm project"
license = "Apache-2.0"
repository = "https://github.com/terra-project/terra-cosmwasm"
homepage = "https://terra.money"
documentation = "https://docs.terra.money"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "0.10.1" }
bigint = "4"
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

